package libc

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/goplus/llgo/internal/crosscompile/compile"
)

const wasmBuiltinsRevision = "1dfe5c302d1c5ab621f7abf04620fae92700fd22"
const wasmBuiltinsRecipe = "dlmalloc-v4"

// GetWasmBuiltinsConfig returns the pinned wasi-libc source used for the
// freestanding WebAssembly builtin library. This is deliberately separate
// from wasi-libc: it provides only the memory and libm helpers that LLVM may
// lower to out-of-line calls, and it must not introduce a WASI Preview 1 ABI.
func GetWasmBuiltinsConfig() compile.LibConfig {
	return compile.LibConfig{
		Name:           "wasmbuiltins",
		Version:        wasmBuiltinsRevision + "-" + wasmBuiltinsRecipe,
		Url:            "https://github.com/WebAssembly/wasi-libc/archive/" + wasmBuiltinsRevision + ".tar.gz",
		ResourceSubDir: "wasi-libc-" + wasmBuiltinsRevision,
	}
}

// PrepareWasmBuiltinsHeaders generates musl's bits/alltypes.h from the two
// templates in the pinned wasi-libc source tree. Keeping this generated header
// inside the versioned source cache makes the library independent of a WASI
// sysroot, which is required by wasm32-unknown-unknown.
func PrepareWasmBuiltinsHeaders(baseDir string) (string, error) {
	includeDir := filepath.Join(baseDir, "llgo-wasmbuiltins-include")
	bitsDir := filepath.Join(includeDir, "bits")
	if err := os.MkdirAll(bitsDir, 0o755); err != nil {
		return "", fmt.Errorf("create wasmbuiltins headers: %w", err)
	}
	muslDir := filepath.Join(baseDir, "libc-top-half", "musl")
	templates := []string{
		filepath.Join(muslDir, "arch", "wasm32", "bits", "alltypes.h.in"),
		filepath.Join(muslDir, "include", "alltypes.h.in"),
	}
	var generated bytes.Buffer
	for _, template := range templates {
		contents, err := os.ReadFile(template)
		if err != nil {
			return "", fmt.Errorf("read wasmbuiltins alltypes template %s: %w", template, err)
		}
		generateMuslAllTypes(&generated, string(contents))
	}
	path := filepath.Join(bitsDir, "alltypes.h")
	if err := os.WriteFile(path, generated.Bytes(), 0o644); err != nil {
		return "", fmt.Errorf("write wasmbuiltins alltypes.h: %w", err)
	}
	// The wasm alltypes template refers to these five lower-half headers for
	// scalar type definitions. Copy only this closed, declaration-only subset;
	// adding the full public directory to the search path would let errno.h pull
	// the Preview 1 wasi/api.h ABI into wasm32-unknown-unknown.
	typeHeaderDir := filepath.Join(baseDir, "libc-bottom-half", "headers", "public")
	for _, name := range []string{
		"__typedef_time_t.h",
		"__typedef_suseconds_t.h",
		"__typedef_clockid_t.h",
		"__typedef_sigset_t.h",
		"__typedef_clock_t.h",
	} {
		source := filepath.Join(typeHeaderDir, name)
		contents, err := os.ReadFile(source)
		if err != nil {
			return "", fmt.Errorf("read wasmbuiltins type header %s: %w", source, err)
		}
		destination := filepath.Join(includeDir, name)
		if err := os.WriteFile(destination, contents, 0o644); err != nil {
			return "", fmt.Errorf("write wasmbuiltins type header %s: %w", destination, err)
		}
	}
	generatedFiles := map[string]string{
		// dlmalloc only needs the two errno values below. A target-local errno
		// state avoids pulling wasi/api.h (Preview 1) into unknown-unknown and
		// remains sufficient for these single-threaded WebAssembly targets.
		"errno.h": `#ifndef LLGO_WASMBUILTINS_ERRNO_H
#define LLGO_WASMBUILTINS_ERRNO_H
extern int errno;
#ifndef EINVAL
#define EINVAL 22
#endif
#ifndef ENOMEM
#define ENOMEM 12
#endif
#endif
`,
		"errno_state.c": `int errno;
`,
		// WebAssembly 1.0 fixes the linear-memory page size at 64 KiB. sbrk.c
		// consumes only this macro from wasi-libc's public header collection.
		"__macro_PAGESIZE.h": `#ifndef LLGO_WASMBUILTINS_PAGESIZE_H
#define LLGO_WASMBUILTINS_PAGESIZE_H
#define PAGESIZE (0x10000)
#endif
`,
	}
	for name, contents := range generatedFiles {
		path := filepath.Join(includeDir, name)
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			return "", fmt.Errorf("write wasmbuiltins support file %s: %w", path, err)
		}
	}
	return includeDir, nil
}

// generateMuslAllTypes implements wasi-libc's pinned mkalltypes.sed script.
// Keeping this tiny transformation in Go avoids making the crosscompiler rely
// on a host sed implementation while retaining the upstream conditional type
// definitions verbatim.
func generateMuslAllTypes(out *bytes.Buffer, template string) {
	for _, line := range strings.SplitAfter(template, "\n") {
		hasNewline := strings.HasSuffix(line, "\n")
		line = strings.TrimSuffix(line, "\n")
		switch {
		case strings.HasPrefix(line, "TYPEDEF ") && strings.HasSuffix(line, ";"):
			declaration := strings.TrimSuffix(strings.TrimPrefix(line, "TYPEDEF "), ";")
			if split := strings.LastIndexByte(declaration, ' '); split >= 0 {
				typeName := declaration[split+1:]
				fmt.Fprintf(out, "#if defined(__NEED_%s) && !defined(__DEFINED_%s)\ntypedef %s;\n#define __DEFINED_%s\n#endif\n\n",
					typeName, typeName, declaration, typeName)
				continue
			}
		case strings.HasPrefix(line, "STRUCT ") && strings.HasSuffix(line, ";"):
			declaration := strings.TrimSuffix(strings.TrimPrefix(line, "STRUCT "), ";")
			if split := strings.IndexByte(declaration, ' '); split >= 0 {
				name := declaration[:split]
				body := declaration[split+1:]
				fmt.Fprintf(out, "#if defined(__NEED_struct_%s) && !defined(__DEFINED_struct_%s)\nstruct %s %s;\n#define __DEFINED_struct_%s\n#endif\n\n",
					name, name, name, body, name)
				continue
			}
		case strings.HasPrefix(line, "UNION ") && strings.HasSuffix(line, ";"):
			declaration := strings.TrimSuffix(strings.TrimPrefix(line, "UNION "), ";")
			if split := strings.IndexByte(declaration, ' '); split >= 0 {
				name := declaration[:split]
				body := declaration[split+1:]
				fmt.Fprintf(out, "#if defined(__NEED_union_%s) && !defined(__DEFINED_union_%s)\nunion %s %s;\n#define __DEFINED_union_%s\n#endif\n\n",
					name, name, name, body, name)
				continue
			}
		}
		out.WriteString(line)
		if hasNewline {
			out.WriteByte('\n')
		}
	}
}

// GetWasmBuiltinsCompileConfig mirrors the deliberately small freestanding
// library used by TinyGo's wasip2 and wasm-unknown targets. The target triple
// is part of the archive name so the WASI and unknown-unknown ABIs can never
// share cached objects.
func GetWasmBuiltinsCompileConfig(baseDir, includeDir, target string) compile.CompileConfig {
	muslDir := filepath.Join(baseDir, "libc-top-half", "musl")
	source := func(parts ...string) string {
		return filepath.Join(append([]string{muslDir, "src"}, parts...)...)
	}
	includeFlags := []string{
		"-I" + filepath.Join(baseDir, "dlmalloc", "include"),
		"-I" + includeDir,
		"-isystem" + filepath.Join(muslDir, "arch", "wasm32"),
		"-isystem" + filepath.Join(muslDir, "arch", "generic"),
		"-isystem" + filepath.Join(muslDir, "src", "internal"),
		"-isystem" + filepath.Join(muslDir, "src", "include"),
		// Clang's builtin stddef.h must precede musl's fallback: wasi-libc's
		// wasm alltypes template deliberately asks it for wchar_t/max_align_t.
		"-idirafter" + filepath.Join(muslDir, "include"),
	}
	groupFlags := append([]string{
		"-Wall",
		"-Wno-unused-but-set-variable",
		"-std=gnu11",
		"-nostdlibinc",
		// Use musl's target-neutral declarations. The patched wasi-libc branch
		// includes Preview 1 wasi/api.h for errno values, which is invalid for
		// wasm32-unknown-unknown and unnecessary for this builtin subset.
		"-D__wasilibc_unmodified_upstream",
		"-mnontrapping-fptoint",
		// The routines must not recursively lower memcpy/memmove/memset back
		// to the very symbols this archive is providing.
		"-mno-bulk-memory",
	}, includeFlags...)

	return compile.CompileConfig{
		Groups: []compile.CompileGroup{{
			OutputFileName: fmt.Sprintf("libwasmbuiltins-%s.a", target),
			Files: []string{
				// wasi-libc's default malloc implementation. Its sbrk backend
				// lowers directly to WebAssembly memory.size/memory.grow and
				// therefore works for both WASI Preview 2 core modules and the
				// unknown-unknown freestanding ABI without Preview 1 imports.
				filepath.Join(baseDir, "dlmalloc", "src", "dlmalloc.c"),
				filepath.Join(baseDir, "libc-bottom-half", "sources", "sbrk.c"),
				filepath.Join(baseDir, "libc-bottom-half", "sources", "errno.c"),
				filepath.Join(includeDir, "errno_state.c"),
				filepath.Join(baseDir, "libc-bottom-half", "sources", "abort.c"),
				source("string", "memcpy.c"),
				source("string", "memmove.c"),
				source("string", "memset.c"),
				source("math", "__math_divzero.c"),
				source("math", "__math_invalid.c"),
				source("math", "__math_oflow.c"),
				source("math", "__math_uflow.c"),
				source("math", "__math_xflow.c"),
				source("math", "exp.c"),
				source("math", "exp_data.c"),
				source("math", "exp2.c"),
				source("math", "log.c"),
				source("math", "log_data.c"),
			},
			CFlags: groupFlags,
		}},
	}
}
