//go:build ignore

package main

import (
	"bytes"
	"crypto/rand"
	"crypto/rsa"
	"fmt"
	"go/format"
	"os"
)

func main() {
	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by go run generate.go; DO NOT EDIT.\n// Public test-only keys: never use these for real encryption or signing.\n\npackage rsafixture\n\nvar keyData = []struct { n, d string; primes []string }{")
	for _, primes := range []int{2, 2, 3} {
		key, err := rsa.GenerateMultiPrimeKey(rand.Reader, primes, 2048)
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&source, "{n: %q, d: %q, primes: []string{", key.N.Text(16), key.D.Text(16))
		for _, prime := range key.Primes {
			fmt.Fprintf(&source, "%q,", prime.Text(16))
		}
		fmt.Fprintln(&source, "}},")
	}
	fmt.Fprintln(&source, "}")
	data, err := format.Source(source.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("keys_generated.go", data, 0644); err != nil {
		panic(err)
	}
}
