// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package runtime

import (
	"unsafe"

	"github.com/goplus/llgo/runtime/abi"
	"github.com/goplus/llgo/runtime/internal/runtime/goarch"
)

//go:linkname closureEnv llgo.closureEnv
func closureEnv() unsafe.Pointer

const (
	c0 = uintptr((8-goarch.PtrSize)/4*2860486313 + (goarch.PtrSize-4)/4*33054211828000289)
	c1 = uintptr((8-goarch.PtrSize)/4*3267000013 + (goarch.PtrSize-4)/4*23344194077549503)
)

func memhash0(p unsafe.Pointer, h uintptr) uintptr {
	return h
}

func memhash8(p unsafe.Pointer, h uintptr) uintptr {
	return memhash(p, h, 1)
}

func memhash16(p unsafe.Pointer, h uintptr) uintptr {
	return memhash(p, h, 2)
}

func memhash128(p unsafe.Pointer, h uintptr) uintptr {
	return memhash(p, h, 16)
}

//go:nosplit
// func memhash_varlen(p unsafe.Pointer, h uintptr) uintptr {
// 	ptr := getclosureptr()
// 	size := *(*uintptr)(unsafe.Pointer(ptr + unsafe.Sizeof(h)))
// 	return memhash(p, h, size)
// }

// in asm_*.s
// func memhash(p unsafe.Pointer, h, s uintptr) uintptr
// func memhash32(p unsafe.Pointer, h uintptr) uintptr
// func memhash64(p unsafe.Pointer, h uintptr) uintptr
// func strhash(p unsafe.Pointer, h uintptr) uintptr

func strhash(a unsafe.Pointer, h uintptr) uintptr {
	x := (*String)(a)
	return memhash(x.data, h, uintptr(x.len))
}

// NOTE: Because NaN != NaN, a map can contain any
// number of (mostly useless) entries keyed with NaNs.
// To avoid long hash chains, we assign a random number
// as the hash value for a NaN.

func f32hash(p unsafe.Pointer, h uintptr) uintptr {
	f := *(*float32)(p)
	switch {
	case f == 0:
		return c1 * (c0 ^ h) // +0, -0
	case f != f:
		return c1 * (c0 ^ h ^ uintptr(fastrand())) // any kind of NaN
	default:
		return memhash(p, h, 4)
	}
}

func f64hash(p unsafe.Pointer, h uintptr) uintptr {
	f := *(*float64)(p)
	switch {
	case f == 0:
		return c1 * (c0 ^ h) // +0, -0
	case f != f:
		return c1 * (c0 ^ h ^ uintptr(fastrand())) // any kind of NaN
	default:
		return memhash(p, h, 8)
	}
}

func c64hash(p unsafe.Pointer, h uintptr) uintptr {
	x := (*[2]float32)(p)
	return f32hash(unsafe.Pointer(&x[1]), f32hash(unsafe.Pointer(&x[0]), h))
}

func c128hash(p unsafe.Pointer, h uintptr) uintptr {
	x := (*[2]float64)(p)
	return f64hash(unsafe.Pointer(&x[1]), f64hash(unsafe.Pointer(&x[0]), h))
}

func interhash(p unsafe.Pointer, h uintptr) uintptr {
	a := (*iface)(p)
	tab := a.tab
	if tab == nil {
		return h
	}
	t := tab._type
	if t.Equal == nil {
		// Check hashability here. We could do this check inside
		// typehash, but we want to report the topmost type in
		// the error text (e.g. in a struct with a field of slice type
		// we want to report the struct, not the slice).
		panic(errorString("hash of unhashable type " + t.String()))
	}
	if isDirectIface(t) {
		return c1 * typehashImpl(t, unsafe.Pointer(&a.data), h^c0)
	} else {
		return c1 * typehashImpl(t, a.data, h^c0)
	}
}

func nilinterhash(p unsafe.Pointer, h uintptr) uintptr {
	a := (*eface)(p)
	t := a._type
	if t == nil {
		return h
	}
	if t.Equal == nil {
		// See comment in interhash above.
		panic(errorString("hash of unhashable type " + t.String()))
	}
	if isDirectIface(t) {
		return c1 * typehashImpl(t, unsafe.Pointer(&a.data), h^c0)
	} else {
		return c1 * typehashImpl(t, a.data, h^c0)
	}
}

// typehash computes the hash of the object of type t at address p.
// h is the seed.
// This function is seldom used. Most maps use for hashing either
// fixed functions (e.g. f32hash) or compiler-generated functions
// (e.g. for a type like struct { x, y string }). This implementation
// is slower but more general and is used for hashing interface types
// (called from interhash or nilinterhash, above) or for hashing in
// maps generated by reflect.MapOf (reflect_typehash, below).
// Note: this function must match the compiler generated
// functions exactly. See issue 37716.
func typehashImpl(t *_type, p unsafe.Pointer, h uintptr) uintptr {
	if t.TFlag&abi.TFlagRegularMemory != 0 {
		// Handle ptr sizes specially, see issue 37086.
		switch t.Size_ {
		case 4:
			return memhash32(p, h)
		case 8:
			return memhash64(p, h)
		default:
			return memhash(p, h, t.Size_)
		}
	}
	switch t.Kind() {
	case abi.Float32:
		return f32hash(p, h)
	case abi.Float64:
		return f64hash(p, h)
	case abi.Complex64:
		return c64hash(p, h)
	case abi.Complex128:
		return c128hash(p, h)
	case abi.String:
		return strhash(p, h)
	case abi.Interface:
		i := (*interfacetype)(unsafe.Pointer(t))
		if len(i.Methods) == 0 {
			return nilinterhash(p, h)
		}
		return interhash(p, h)
	case abi.Array:
		a := (*arraytype)(unsafe.Pointer(t))
		for i := uintptr(0); i < a.Len; i++ {
			h = typehashImpl(a.Elem, add(p, i*a.Elem.Size_), h)
		}
		return h
	case abi.Struct:
		s := (*structtype)(unsafe.Pointer(t))
		for _, f := range s.Fields {
			if f.Name_ == "_" {
				continue
			}
			h = typehashImpl(f.Typ, add(p, f.Offset), h)
		}
		return h
	default:
		// Should never happen, as typehash should only be called
		// with comparable types.
		panic(errorString("hash of unhashable type " + t.String()))
	}
}

//llgo:env
func typehash(p unsafe.Pointer, h uintptr) uintptr {
	return typehashImpl((*_type)(closureEnv()), p, h)
}

func memequalptr(p, q unsafe.Pointer) bool {
	return *(*uintptr)(p) == *(*uintptr)(q)
}
func memequal0(p, q unsafe.Pointer) bool {
	return true
}
func memequal8(p, q unsafe.Pointer) bool {
	return *(*int8)(p) == *(*int8)(q)
}
func memequal16(p, q unsafe.Pointer) bool {
	return *(*int16)(p) == *(*int16)(q)
}
func memequal32(p, q unsafe.Pointer) bool {
	return *(*int32)(p) == *(*int32)(q)
}
func memequal64(p, q unsafe.Pointer) bool {
	return *(*int64)(p) == *(*int64)(q)
}
func memequal128(p, q unsafe.Pointer) bool {
	return *(*[2]int64)(p) == *(*[2]int64)(q)
}
func f32equal(p, q unsafe.Pointer) bool {
	return *(*float32)(p) == *(*float32)(q)
}
func f64equal(p, q unsafe.Pointer) bool {
	return *(*float64)(p) == *(*float64)(q)
}
func c64equal(p, q unsafe.Pointer) bool {
	return *(*complex64)(p) == *(*complex64)(q)
}
func c128equal(p, q unsafe.Pointer) bool {
	return *(*complex128)(p) == *(*complex128)(q)
}
func strequal(p, q unsafe.Pointer) bool {
	return *(*string)(p) == *(*string)(q)
}
func interequal(p, q unsafe.Pointer) bool {
	x := *(*iface)(p)
	y := *(*iface)(q)
	return x.tab == y.tab && ifaceeq(x.tab, x.data, y.data)
}
func nilinterequal(p, q unsafe.Pointer) bool {
	x := *(*eface)(p)
	y := *(*eface)(q)
	return x._type == y._type && efaceeq(x._type, x.data, y.data)
}

// typeequal compares the values of type t at p and q without calling the
// equality callback stored in t. LLGo emits those callbacks in runtime type
// descriptors for compatibility with the Go ABI, but a callback invocation is
// an opaque indirect call to coroutine analysis. The descriptor itself carries
// all information needed to perform the same comparison with static calls.
//
// Keep this in step with typehash above: map keys accepted by typehash must use
// the same equality relation here. In particular, floating-point zeroes compare
// equal, NaNs compare unequal, blank struct fields are ignored, and comparing
// an interface containing an uncomparable value panics.
func typeequal(t *_type, p, q unsafe.Pointer) bool {
	if t.TFlag&abi.TFlagRegularMemory != 0 {
		return memequal(p, q, t.Size_, t.Align_)
	}

	switch t.Kind() {
	case abi.Bool, abi.Int8, abi.Uint8:
		return memequal8(p, q)
	case abi.Int16, abi.Uint16:
		return memequal16(p, q)
	case abi.Int32, abi.Uint32:
		return memequal32(p, q)
	case abi.Int64, abi.Uint64:
		return memequal64(p, q)
	case abi.Int, abi.Uint, abi.Uintptr:
		return memequal(p, q, t.Size_, t.Align_)
	case abi.Float32:
		return f32equal(p, q)
	case abi.Float64:
		return f64equal(p, q)
	case abi.Complex64:
		return c64equal(p, q)
	case abi.Complex128:
		return c128equal(p, q)
	case abi.Chan, abi.Pointer, abi.UnsafePointer:
		return memequalptr(p, q)
	case abi.String:
		return strequal(p, q)
	case abi.Interface:
		i := (*interfacetype)(unsafe.Pointer(t))
		if len(i.Methods) == 0 {
			return nilinterequal(p, q)
		}
		return interequal(p, q)
	case abi.Array:
		return arrayequalImpl((*arraytype)(unsafe.Pointer(t)), p, q)
	case abi.Struct:
		return structequalImpl((*structtype)(unsafe.Pointer(t)), p, q)
	default:
		panic(errorString("comparing uncomparable type " + t.Str_))
	}
}

func memequal(p, q unsafe.Pointer, size uintptr, align uint8) bool {
	switch size {
	case 0:
		return true
	case 1:
		return memequal8(p, q)
	case 2:
		if align >= 2 {
			return memequal16(p, q)
		}
	case 4:
		if align >= 4 {
			return memequal32(p, q)
		}
	case 8:
		if align >= 8 {
			return memequal64(p, q)
		}
	case 16:
		if align >= 8 {
			return memequal128(p, q)
		}
	}
	for i := uintptr(0); i < size; i++ {
		if *(*byte)(add(p, i)) != *(*byte)(add(q, i)) {
			return false
		}
	}
	return true
}

func efaceeq(t *_type, x, y unsafe.Pointer) bool {
	if t == nil {
		return true
	}
	if t.Equal == nil {
		panic(errorString("comparing uncomparable type " + t.Str_))
	}
	if isDirectIface(t) {
		// Direct interface types are ptr, chan, map, func, and single-element structs/arrays thereof.
		// Maps and funcs are not comparable, so they can't reach here.
		// Ptrs, chans, and single-element items can be compared directly using ==.
		return x == y
	}
	return typeequal(t, x, y)
}
func ifaceeq(tab *itab, x, y unsafe.Pointer) bool {
	if tab == nil {
		return true
	}
	t := tab._type
	if t.Equal == nil {
		panic(errorString("comparing uncomparable type " + t.Str_))
	}
	if isDirectIface(t) {
		// See comment in efaceeq.
		return x == y
	}
	return typeequal(t, x, y)
}

func structFieldsHaveCheapMismatch(fields []structfield, p, q unsafe.Pointer) bool {
	for _, ft := range fields {
		if ft.Name_ == "_" {
			continue
		}
		pi := add(p, ft.Offset)
		qi := add(q, ft.Offset)
		if typeHasCheapMismatch(ft.Typ, pi, qi) {
			return true
		}
	}
	return false
}

func typeHasCheapMismatch(t *_type, p, q unsafe.Pointer) bool {
	switch t.Kind() {
	case abi.Bool,
		abi.Int, abi.Int8, abi.Int16, abi.Int32, abi.Int64,
		abi.Uint, abi.Uint8, abi.Uint16, abi.Uint32, abi.Uint64, abi.Uintptr,
		abi.Float32, abi.Float64, abi.Complex64, abi.Complex128,
		abi.Pointer, abi.Chan, abi.UnsafePointer:
		return !typeequal(t, p, q)
	case abi.String:
		return len(*(*string)(p)) != len(*(*string)(q))
	case abi.Struct:
		return structFieldsHaveCheapMismatch((*structtype)(unsafe.Pointer(t)).Fields, p, q)
	case abi.Array:
		x := (*arraytype)(unsafe.Pointer(t))
		elem := x.Elem
		for i := uintptr(0); i < x.Len; i++ {
			pi := add(p, i*elem.Size_)
			qi := add(q, i*elem.Size_)
			if typeHasCheapMismatch(elem, pi, qi) {
				return true
			}
		}
	}
	return false
}

func typeEqualMayPanic(t *_type) bool {
	switch t.Kind() {
	case abi.Interface:
		return true
	case abi.Struct:
		x := (*structtype)(unsafe.Pointer(t))
		for _, ft := range x.Fields {
			if ft.Name_ != "_" && typeEqualMayPanic(ft.Typ) {
				return true
			}
		}
	case abi.Array:
		return typeEqualMayPanic((*arraytype)(unsafe.Pointer(t)).Elem)
	}
	return false
}

func structequalImpl(x *structtype, p, q unsafe.Pointer) bool {
	fields := x.Fields
	segmentStart := 0
	for i, ft := range fields {
		if ft.Name_ == "_" {
			continue
		}
		if !typeEqualMayPanic(ft.Typ) {
			continue
		}
		if structFieldsHaveCheapMismatch(fields[segmentStart:i], p, q) {
			return false
		}
		for _, ft := range fields[segmentStart : i+1] {
			if ft.Name_ == "_" {
				continue
			}
			pi := add(p, ft.Offset)
			qi := add(q, ft.Offset)
			if !typeequal(ft.Typ, pi, qi) {
				return false
			}
		}
		segmentStart = i + 1
	}
	if structFieldsHaveCheapMismatch(fields[segmentStart:], p, q) {
		return false
	}
	for _, ft := range fields[segmentStart:] {
		if ft.Name_ == "_" {
			continue
		}
		pi := add(p, ft.Offset)
		qi := add(q, ft.Offset)
		if !typeequal(ft.Typ, pi, qi) {
			return false
		}
	}
	return true
}

//llgo:env
func structequal(p, q unsafe.Pointer) bool {
	return structequalImpl((*structtype)(closureEnv()), p, q)
}

func arrayequalImpl(x *arraytype, p, q unsafe.Pointer) bool {
	elem := x.Elem
	for i := uintptr(0); i < x.Len; i++ {
		pi := add(p, i*elem.Size_)
		qi := add(q, i*elem.Size_)
		if !typeequal(elem, pi, qi) {
			return false
		}
	}
	return true
}

//llgo:env
func arrayequal(p, q unsafe.Pointer) bool {
	return arrayequalImpl((*arraytype)(closureEnv()), p, q)
}

// Testing adapters for hash quality tests (see hash_test.go)
func stringHash(s string, seed uintptr) uintptr {
	return strhash(noescape(unsafe.Pointer(&s)), seed)
}

func bytesHash(b []byte, seed uintptr) uintptr {
	s := (*slice)(unsafe.Pointer(&b))
	return memhash(s.array, seed, uintptr(s.len))
}

func int32Hash(i uint32, seed uintptr) uintptr {
	return memhash32(noescape(unsafe.Pointer(&i)), seed)
}

func int64Hash(i uint64, seed uintptr) uintptr {
	return memhash64(noescape(unsafe.Pointer(&i)), seed)
}

func efaceHash(i any, seed uintptr) uintptr {
	return nilinterhash(noescape(unsafe.Pointer(&i)), seed)
}

func ifaceHash(i interface {
	F()
}, seed uintptr) uintptr {
	return interhash(noescape(unsafe.Pointer(&i)), seed)
}

var hashkey [4]uintptr

// Note: These routines perform the read with a native endianness.
func readUnaligned32(p unsafe.Pointer) uint32 {
	q := (*[4]byte)(p)
	if goarch.BigEndian {
		return uint32(q[3]) | uint32(q[2])<<8 | uint32(q[1])<<16 | uint32(q[0])<<24
	}
	return uint32(q[0]) | uint32(q[1])<<8 | uint32(q[2])<<16 | uint32(q[3])<<24
}

func readUnaligned64(p unsafe.Pointer) uint64 {
	q := (*[8]byte)(p)
	if goarch.BigEndian {
		return uint64(q[7]) | uint64(q[6])<<8 | uint64(q[5])<<16 | uint64(q[4])<<24 |
			uint64(q[3])<<32 | uint64(q[2])<<40 | uint64(q[1])<<48 | uint64(q[0])<<56
	}
	return uint64(q[0]) | uint64(q[1])<<8 | uint64(q[2])<<16 | uint64(q[3])<<24 | uint64(q[4])<<32 | uint64(q[5])<<40 | uint64(q[6])<<48 | uint64(q[7])<<56
}
