name: Publish baseline benchmarks

on:
  workflow_run:
    workflows: [Baseline benchmarks]
    types: [completed]

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    uses: dastai/setup-benchmark-go-action/.github/workflows/publish.yml@6d4d1e394e5b0116de360cabd70c747f6b5507fc
    with:
      run_id: ${{ github.event.workflow_run.id }}
      config_path: .github/llgo-benchmark.yml
