name: Release Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Populate Darwin sysroot
        run: bash .github/workflows/populate_darwin_sysroot.sh
      - name: Populate Linux sysroot
        run: bash .github/workflows/populate_linux_sysroot.sh
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{github.token}}
        run: |
          docker run \
            --rm \
            -e GITHUB_TOKEN=${GITHUB_TOKEN} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd):/go/src/llgo \
            -w /go/src/llgo \
            ghcr.io/goreleaser/goreleaser-cross:v1.22 \
            release --clean --skip nfpm,snapcraft
